remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
title: Test
description: Leap Day is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day